const initState = {
  guitars: [
    {
      id: 1,
      type: "electric",
      name: "Squier By Fender Vintage BLK",
      text: `With a body based off of one of the most notable guitars in history and dressed in vintage white, the Squier Vintage Modified ‘70s Stratocaster electric guitar looks wonderfully familiar. Squier tweaks the classic to give it a custom look and feel. Modified means adding new twists to familiar designs. Squier's Vintage Modified series excels at just that, imparting hot-output chop-shop sound, feel and value to traditional instrument designs.`,
      description: [
        `Model #: 1148100559, Series: Standard, Body: Alder, Neck Material: Maple, Neck Shape: Modern "C", Scale Length: 25.5" (648 mm), Fingerboard: Rosewood, Number of Frets: 22, Frets Size: Medium Jumbo, Bridge Pickup: Hot Vintage Alnico Humbucking, Neck Pickup: Hot Vintage Alnico Humbucking, ontrols: Master Volume, Tone 1. (Neck Pickup), Tone 2. (Middle Pickup), Bridge: Floyd Rose® Special Double Locking 2-Point Tremolo.`,
      ],
      price: 380,
      img: "stratEbony",
    },
    {
      id: 2,
      type: "electric",
      name: "Squier By Fender Vintage SFG",
      text: `With a body based off of one of the most notable guitars in history and dressed in vintage white, the Squier Vintage Modified ‘70s Stratocaster electric guitar looks wonderfully familiar. Squier tweaks the classic to give it a custom look and feel. Modified means adding new twists to familiar designs. Squier's Vintage Modified series excels at just that, imparting hot-output chop-shop sound, feel and value to traditional instrument designs.`,
      description: [
        `Model #: 1148100559, Series: Standard, Body: Alder, Neck Material: Maple, Neck Shape: Modern "C", Scale Length: 25.5" (648 mm), Fingerboard: Rosewood, Number of Frets: 22, Frets Size: Medium Jumbo, Bridge Pickup: Hot Vintage Alnico Humbucking, Neck Pickup: Hot Vintage Alnico Humbucking, ontrols: Master Volume, Tone 1. (Neck Pickup), Tone 2. (Middle Pickup), Bridge: Floyd Rose® Special Double Locking 2-Point Tremolo.`,
      ],
      price: 367,
      img: "stratLight",
    },
    {
      id: 3,
      type: "electric",
      name: "Epiphone Les Paul Ultra-III",
      text: `With a body based off of one of the most notable guitars in history and dressed in vintage white, the Squier Vintage Modified ‘70s Stratocaster electric guitar looks wonderfully familiar. Squier tweaks the classic to give it a custom look and feel. Modified means adding new twists to familiar designs. Squier's Vintage Modified series excels at just that, imparting hot-output chop-shop sound, feel and value to traditional instrument designs.`,
      description: [
        `Model #: 1148100559, Series: Standard, Body: Alder, Neck Material: Maple, Neck Shape: Modern "C", Scale Length: 25.5" (648 mm), Fingerboard: Rosewood, Number of Frets: 22, Frets Size: Medium Jumbo, Bridge Pickup: Hot Vintage Alnico Humbucking, Neck Pickup: Hot Vintage Alnico Humbucking, ontrols: Master Volume, Tone 1. (Neck Pickup), Tone 2. (Middle Pickup), Bridge: Floyd Rose® Special Double Locking 2-Point Tremolo.`,
      ],
      price: 780,
      img: "epiEbony",
    },
    {
      id: 4,
      type: "electric",
      name: "Epiphone Les Paul Tribute",
      text: `With a body based off of one of the most notable guitars in history and dressed in vintage white, the Squier Vintage Modified ‘70s Stratocaster electric guitar looks wonderfully familiar. Squier tweaks the classic to give it a custom look and feel. Modified means adding new twists to familiar designs. Squier's Vintage Modified series excels at just that, imparting hot-output chop-shop sound, feel and value to traditional instrument designs.`,
      description: [
        `Model #: 1148100559, Series: Standard, Body: Alder, Neck Material: Maple, Neck Shape: Modern "C", Scale Length: 25.5" (648 mm), Fingerboard: Rosewood, Number of Frets: 22, Frets Size: Medium Jumbo, Bridge Pickup: Hot Vintage Alnico Humbucking, Neck Pickup: Hot Vintage Alnico Humbucking, ontrols: Master Volume, Tone 1. (Neck Pickup), Tone 2. (Middle Pickup), Bridge: Floyd Rose® Special Double Locking 2-Point Tremolo.`,
      ],
      price: 780,
      img: "epiChery",
    },
    {
      id: 5,
      type: "electric",
      name: "Ibanez RG721RW-CNF  ",
      text: `With a body based off of one of the most notable guitars in history and dressed in vintage white, the Squier Vintage Modified ‘70s Stratocaster electric guitar looks wonderfully familiar. Squier tweaks the classic to give it a custom look and feel. Modified means adding new twists to familiar designs. Squier's Vintage Modified series excels at just that, imparting hot-output chop-shop sound, feel and value to traditional instrument designs.`,
      description: [
        `Model #: 1148100559, Series: Standard, Body: Alder, Neck Material: Maple, Neck Shape: Modern "C", Scale Length: 25.5" (648 mm), Fingerboard: Rosewood, Number of Frets: 22, Frets Size: Medium Jumbo, Bridge Pickup: Hot Vintage Alnico Humbucking, Neck Pickup: Hot Vintage Alnico Humbucking, ontrols: Master Volume, Tone 1. (Neck Pickup), Tone 2. (Middle Pickup), Bridge: Floyd Rose® Special Double Locking 2-Point Tremolo.`,
      ],
      price: 800,
      img: "ibanezBrown",
    },
    {
      id: 6,
      type: "electric",
      name: "Ibanez SA360QM-TRB  ",
      text: `With a body based off of one of the most notable guitars in history and dressed in vintage white, the Squier Vintage Modified ‘70s Stratocaster electric guitar looks wonderfully familiar. Squier tweaks the classic to give it a custom look and feel. Modified means adding new twists to familiar designs. Squier's Vintage Modified series excels at just that, imparting hot-output chop-shop sound, feel and value to traditional instrument designs.`,
      description: [
        `Model #: 1148100559, Series: Standard, Body: Alder, Neck Material: Maple, Neck Shape: Modern "C", Scale Length: 25.5" (648 mm), Fingerboard: Rosewood, Number of Frets: 22, Frets Size: Medium Jumbo, Bridge Pickup: Hot Vintage Alnico Humbucking, Neck Pickup: Hot Vintage Alnico Humbucking, ontrols: Master Volume, Tone 1. (Neck Pickup), Tone 2. (Middle Pickup), Bridge: Floyd Rose® Special Double Locking 2-Point Tremolo.`,
      ],
      price: 540,
      img: "ibanezRed",
    },
    {
      id: 7,
      type: "acoustic",
      name: "Takamine GD71-BSB",
      text: `With a body based off of one of the most notable guitars in history and dressed in vintage white, the Squier Vintage Modified ‘70s Stratocaster electric guitar looks wonderfully familiar. Squier tweaks the classic to give it a custom look and feel. Modified means adding new twists to familiar designs. Squier's Vintage Modified series excels at just that, imparting hot-output chop-shop sound, feel and value to traditional instrument designs.`,
      description: [
        `Model #: 1148100559, Series: Standard, Body: Alder, Neck Material: Maple, Neck Shape: Modern "C", Scale Length: 25.5" (648 mm), Fingerboard: Rosewood, Number of Frets: 22, Frets Size: Medium Jumbo, Bridge Pickup: Hot Vintage Alnico Humbucking, Neck Pickup: Hot Vintage Alnico Humbucking, ontrols: Master Volume, Tone 1. (Neck Pickup), Tone 2. (Middle Pickup), Bridge: Floyd Rose® Special Double Locking 2-Point Tremolo.`,
      ],
      price: 350,
      img: "takamine",
    },
    {
      id: 8,
      type: "acoustic",
      name: "Yamaha FJX720SC Black",
      text: `With a body based off of one of the most notable guitars in history and dressed in vintage white, the Squier Vintage Modified ‘70s Stratocaster electric guitar looks wonderfully familiar. Squier tweaks the classic to give it a custom look and feel. Modified means adding new twists to familiar designs. Squier's Vintage Modified series excels at just that, imparting hot-output chop-shop sound, feel and value to traditional instrument designs.`,
      description: [
        `Model #: 1148100559, Series: Standard, Body: Alder, Neck Material: Maple, Neck Shape: Modern "C", Scale Length: 25.5" (648 mm), Fingerboard: Rosewood, Number of Frets: 22, Frets Size: Medium Jumbo, Bridge Pickup: Hot Vintage Alnico Humbucking, Neck Pickup: Hot Vintage Alnico Humbucking, ontrols: Master Volume, Tone 1. (Neck Pickup), Tone 2. (Middle Pickup), Bridge: Floyd Rose® Special Double Locking 2-Point Tremolo.`,
      ],
      price: 559,
      img: "yamahaBlack",
    },
    {
      id: 9,
      type: "acoustic",
      name: "Yamaha FS720S Natural",
      text: `With a body based off of one of the most notable guitars in history and dressed in vintage white, the Squier Vintage Modified ‘70s Stratocaster electric guitar looks wonderfully familiar. Squier tweaks the classic to give it a custom look and feel. Modified means adding new twists to familiar designs. Squier's Vintage Modified series excels at just that, imparting hot-output chop-shop sound, feel and value to traditional instrument designs.`,
      description: [
        `Model #: 1148100559, Series: Standard, Body: Alder, Neck Material: Maple, Neck Shape: Modern "C", Scale Length: 25.5" (648 mm), Fingerboard: Rosewood, Number of Frets: 22, Frets Size: Medium Jumbo, Bridge Pickup: Hot Vintage Alnico Humbucking, Neck Pickup: Hot Vintage Alnico Humbucking, ontrols: Master Volume, Tone 1. (Neck Pickup), Tone 2. (Middle Pickup), Bridge: Floyd Rose® Special Double Locking 2-Point Tremolo.`,
      ],
      price: 390,
      img: "yamahaNatural",
    },
    {
      id: 10,
      type: "acoustic",
      name: "Martin GPCX1AE",
      text: `With a body based off of one of the most notable guitars in history and dressed in vintage white, the Squier Vintage Modified ‘70s Stratocaster electric guitar looks wonderfully familiar. Squier tweaks the classic to give it a custom look and feel. Modified means adding new twists to familiar designs. Squier's Vintage Modified series excels at just that, imparting hot-output chop-shop sound, feel and value to traditional instrument designs.`,
      description: [
        `Model #: 1148100559, Series: Standard, Body: Alder, Neck Material: Maple, Neck Shape: Modern "C", Scale Length: 25.5" (648 mm), Fingerboard: Rosewood, Number of Frets: 22, Frets Size: Medium Jumbo, Bridge Pickup: Hot Vintage Alnico Humbucking, Neck Pickup: Hot Vintage Alnico Humbucking, ontrols: Master Volume, Tone 1. (Neck Pickup), Tone 2. (Middle Pickup), Bridge: Floyd Rose® Special Double Locking 2-Point Tremolo.`,
      ],
      price: 1180,
      img: "martinNatural",
    },
    {
      id: 11,
      type: "acoustic",
      name: "Martin 000RS1  ",
      text: `With a body based off of one of the most notable guitars in history and dressed in vintage white, the Squier Vintage Modified ‘70s Stratocaster electric guitar looks wonderfully familiar. Squier tweaks the classic to give it a custom look and feel. Modified means adding new twists to familiar designs. Squier's Vintage Modified series excels at just that, imparting hot-output chop-shop sound, feel and value to traditional instrument designs.`,
      description: [
        `Model #: 1148100559, Series: Standard, Body: Alder, Neck Material: Maple, Neck Shape: Modern "C", Scale Length: 25.5" (648 mm), Fingerboard: Rosewood, Number of Frets: 22, Frets Size: Medium Jumbo, Bridge Pickup: Hot Vintage Alnico Humbucking, Neck Pickup: Hot Vintage Alnico Humbucking, ontrols: Master Volume, Tone 1. (Neck Pickup), Tone 2. (Middle Pickup), Bridge: Floyd Rose® Special Double Locking 2-Point Tremolo.`,
      ],
      price: 1140,
      img: "martinSapele",
    },
    {
      id: 12,
      type: "acoustic",
      name: "Ibanez AW300ECE-NT ",
      text: `With a body based off of one of the most notable guitars in history and dressed in vintage white, the Squier Vintage Modified ‘70s Stratocaster electric guitar looks wonderfully familiar. Squier tweaks the classic to give it a custom look and feel. Modified means adding new twists to familiar designs. Squier's Vintage Modified series excels at just that, imparting hot-output chop-shop sound, feel and value to traditional instrument designs.`,
      description: [
        `Model #: 1148100559, Series: Standard, Body: Alder, Neck Material: Maple, Neck Shape: Modern "C", Scale Length: 25.5" (648 mm), Fingerboard: Rosewood, Number of Frets: 22, Frets Size: Medium Jumbo, Bridge Pickup: Hot Vintage Alnico Humbucking, Neck Pickup: Hot Vintage Alnico Humbucking, ontrols: Master Volume, Tone 1. (Neck Pickup), Tone 2. (Middle Pickup), Bridge: Floyd Rose® Special Double Locking 2-Point Tremolo.`,
      ],
      price: 440,
      img: "ibanezNatural",
    },
  ],
  strings: [
    {
      id: 30,
      name: "D'Addario EXL120",
      text: `XL Nickel Wound, D'Addario's most popular electric guitar strings, are precision wound with nickelplated steel onto a carefully drawn, hexagonally shaped, high carbon steel core. The result, strings with long lasting, distinctive bright tone and excellent intonation, is ideal for the widest variety of guitars and musical styles.`,
      description: [
        `Super light gauges for maximum flexibility and biting tone, 
        Round wound with nickelplated steel for distinctive bright tone, 
        Environmentally friendly, corrosion resistant packaging for strings that are always fresh,
        Made in the U.S.A. for the highest quality and performance,
        String Gauges: Plain Steel .009, .011, .016, Nickel Wound .024, .032, .042.`,
      ],
      price: 9,
      img: "d1",
    },
    {
      id: 31,
      name: "D'Addario ECG24",
      text: `XL Nickel Wound, D'Addario's most popular electric guitar strings, are precision wound with nickelplated steel onto a carefully drawn, hexagonally shaped, high carbon steel core. The result, strings with long lasting, distinctive bright tone and excellent intonation, is ideal for the widest variety of guitars and musical styles.`,
      description: [
        `Super light gauges for maximum flexibility and biting tone, 
        Round wound with nickelplated steel for distinctive bright tone, 
        Environmentally friendly, corrosion resistant packaging for strings that are always fresh,
        Made in the U.S.A. for the highest quality and performance,
        String Gauges: Plain Steel .009, .011, .016, Nickel Wound .024, .032, .042.`,
      ],
      price: 10,
      img: "d2",
    },
    {
      id: 32,
      name: "Ernie Ball P02623",
      text: `Ernie Ball 2623 Super Slinky 7-String Electric Guitar Strings are made from nickel-plated steel wire wrapped around tin-plated hex-shaped steel core wire. They produce a well-balanced all around good sound.
      Ernie Ball strings are precision manufactured to the highest standards and most exacting specs to assure consistency, optimum performance, and long life.
      `,
      description: [
        `Super light gauges for maximum flexibility and biting tone, 
        Round wound with nickelplated steel for distinctive bright tone, 
        Environmentally friendly, corrosion resistant packaging for strings that are always fresh,
        Made in the U.S.A. for the highest quality and performance,
        String Gauges: Plain Steel .009, .011, .016, Nickel Wound .024, .032, .042.`,
      ],
      price: 9,
      img: "e1",
    },
    {
      id: 33,
      name: "Ernie Ball P02655",
      text: `Ernie Ball 2655 Super Slinky 7-String Electric Guitar Strings are made from nickel-plated steel wire wrapped around tin-plated hex-shaped steel core wire. They produce a well-balanced all around good sound.
      Ernie Ball strings are precision manufactured to the highest standards and most exacting specs to assure consistency, optimum performance, and long life.
      `,
      description: [
        `Super light gauges for maximum flexibility and biting tone, 
        Round wound with nickelplated steel for distinctive bright tone, 
        Environmentally friendly, corrosion resistant packaging for strings that are always fresh,
        Made in the U.S.A. for the highest quality and performance,
        String Gauges: Plain Steel .009, .011, .016, Nickel Wound .024, .032, .042.`,
      ],
      price: 10,
      img: "e3",
    },
    {
      id: 34,
      name: "Elixir NANOWEB",
      text: `Elixir® Strings deliver the presence, punch, and detail of traditional electric guitar strings. But when it comes to tone life, there is no comparison. Players report with Elixir® Strings their tone lasts longer than any other string, uncoated or coated. The result, strings with long lasting.`,
      description: [
        `Super light gauges for maximum flexibility and biting tone, 
        Round wound with nickelplated steel for distinctive bright tone, 
        Environmentally friendly, corrosion resistant packaging for strings that are always fresh,
        Made in the U.S.A. for the highest quality and performance,
        String Gauges: Plain Steel .009, .011, .016, Nickel Wound .024, .032, .042.`,
      ],
      price: 12,
      img: "el1",
    },
    {
      id: 35,
      name: "Elixir NANOWEB",
      text: `Elixir® Strings deliver the presence, punch, and detail of traditional electric guitar strings. But when it comes to tone life, there is no comparison. Players report with Elixir® Strings their tone lasts longer than any other string, uncoated or coated. The result, strings with long lasting.`,
      description: [
        `Super light gauges for maximum flexibility and biting tone, 
        Round wound with nickelplated steel for distinctive bright tone, 
        Environmentally friendly, corrosion resistant packaging for strings that are always fresh,
        Made in the U.S.A. for the highest quality and performance,
        String Gauges: Plain Steel .009, .011, .016, Nickel Wound .024, .032, .042.`,
      ],
      price: 15,
      img: "el2",
    },
    {
      id: 36,
      name: "Dunlop DHCN1060 ",
      text: `Dunlop Zakk Wylde Icon Series žice za električnu gitaru su razvijene da izdrže torturu koju nad njima sprovodi neprikosnoveni vladar metal gitare. Obimna istraživanja i kritična testiranja od strane Zakk-a lično usavršili su formulu koja funkcioniše za najteže ruke rock muzike. Zakk Wylde Signature.`,
      description: [
        `Super light gauges for maximum flexibility and biting tone, 
        Round wound with nickelplated steel for distinctive bright tone, 
        Environmentally friendly, corrosion resistant packaging for strings that are always fresh,
        Made in the U.S.A. for the highest quality and performance,
        String Gauges: Plain Steel .009, .011, .016, Nickel Wound .024, .032, .042.`,
      ],
      price: 9,
      img: "da1",
    },
    {
      id: 37,
      name: "Dunlop DHCN1060 ",
      text: `Dunlop Zakk Wylde Icon Series žice za električnu gitaru su razvijene da izdrže torturu koju nad njima sprovodi neprikosnoveni vladar metal gitare. Obimna istraživanja i kritična testiranja od strane Zakk-a lično usavršili su formulu koja funkcioniše za najteže ruke rock muzike. Zakk Wylde Signature.`,
      description: [
        `Super light gauges for maximum flexibility and biting tone, 
        Round wound with nickelplated steel for distinctive bright tone, 
        Environmentally friendly, corrosion resistant packaging for strings that are always fresh,
        Made in the U.S.A. for the highest quality and performance,
        String Gauges: Plain Steel .009, .011, .016, Nickel Wound .024, .032, .042.`,
      ],
      price: 9,
      img: "da2",
    },
  ],
  displayInstrument: {},
  inCart: [],
  itemAddedToCart: {},
  personalInfo: {},
  buy: [],
};

export default initState;
